- .github/workflows/test.yaml
- README.md
- package.json
- src/types/ActionInputParameters.ts
- yarn.lock
- Added Github actions for automatically running tests and checking formatting.
- Added `release-it` as a dev dependency to make tagging / releasing easier.
> Add Github actions to test/check formatting, add release-it dependency

- package.json
- src/server-types.ts
- src/types/DisplayDefinition.ts
Add an optional category to the component definition.
> Optional Component Category

- package.json
- src/types/Credential.ts
Needed for upcoming demo, and probably just a good thing to have in general.
[ch7652]
> Support custom headers in OAuth2 credentials

- package.json
- src/index.ts
[ch7697]
Handle `inputs: null`. I didn't go as far as making `inputs` optional, as that seemed like it would potentially be a much more far-reaching change.
> Minor bug fix to handle null action inputs

- package.json
- src/types/server-types.ts
Hoping this is the last type I need to export for a while...
> Export TriggerPayload type

- package.json
- src/testing.ts
- src/types/ActionDefinition.ts
- src/types/ActionLogger.ts
- src/types/ActionPerformFunction.ts
- src/types/ActionPerformReturn.ts
- src/types/TriggerDefinition.ts
- src/types/TriggerResult.ts
- src/types/server-types.ts
* Add support for executionState
* Add support for continuous loops, loop break
* Add missing log levels for trace, metric
> Various Enhancements and minor fixes

- package.json
- src/clients/soap/types.ts
- src/clients/soap/utils.ts
- Document SOAP client types and utility functions
- Clean up some function overloading
- Ensure SOAP components can be tested on Windows systems
> Document and clean up SOAP client types and utility functions

- packages/spectral/src/types/ActionLogger.ts
- packages/spectral/src/types/conditional-logic.ts
> Fix: Update urls causing 301s

- packages/spectral/package.json
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/testing.ts
- packages/spectral/src/types/TriggerPayload.ts
Allow spectral to expose path fragments from trigger calls.
> Update spectral for path fragement

- packages/spectral/package.json
- packages/spectral/src/clients/http/index.ts
- packages/spectral/src/clients/http/inputs.ts
- packages/spectral/src/serverTypes/perform.ts
- packages/spectral/src/util.test.ts
- packages/spectral/src/util.ts
- yarn.lock
Improve input handling, add helpers for more dynamically constructing a
client and easing configuration burden, and make it far easier to add
raw request functionality.
> Enhance HTTP client

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/component/index.ts
- packages/generator-spectral/src/generators/component/templates/src/index.test.ts
- packages/generator-spectral/src/generators/component/templates/src/index.ts
- packages/generator-spectral/src/generators/dataSource/index.ts
- packages/generator-spectral/src/generators/dataSource/templates/dataSource.ts
- packages/spectral/package.json
- packages/spectral/src/harness-testing.test.ts
- packages/spectral/src/index.ts
- packages/spectral/src/invoke-testing.test.ts
- packages/spectral/src/serverTypes/convert.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/testing.ts
- packages/spectral/src/types/ActionPerformReturn.ts
- packages/spectral/src/types/ComponentDefinition.ts
- packages/spectral/src/types/DataSourceDefinition.ts
- packages/spectral/src/types/DataSourcePerformFunction.ts
- packages/spectral/src/types/DataSourceResult.ts
- packages/spectral/src/types/DataSourceType.ts
- packages/spectral/src/types/Inputs.ts
- packages/spectral/src/types/index.ts
- packages/spectral/src/util.test.ts
- packages/spectral/src/util.ts
> Data Source Preview

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/dataSource/templates/dataSource.ts
- packages/spectral/package.json
- packages/spectral/src/harness-testing.test.ts
- packages/spectral/src/invoke-testing.test.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/serverTypes/perform.ts
- packages/spectral/src/testing.ts
- packages/spectral/src/types/ActionPerformFunction.ts
- packages/spectral/src/types/Customer.ts
- packages/spectral/src/types/DataSourcePerformFunction.ts
- packages/spectral/src/types/Instance.ts
- packages/spectral/src/types/TriggerPayload.ts
- packages/spectral/src/types/index.ts
* Simplify Data Source Perform functions
* Add a few missing types
* Minor bug fixes
> More Data Source improvements

- packages/generator-spectral/package.json
- packages/spectral/package.json
- packages/spectral/src/types/DataSourceDefinition.ts
- packages/spectral/src/types/DataSourceResult.ts
- packages/spectral/src/types/Inputs.ts
* Added optional detailDataSource to Data Sources
* Docstring clarifications
> Additional Data Source improvements

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/dataSource/templates/dataSource.ts
- packages/spectral/package.json
- packages/spectral/src/harness-testing.test.ts
- packages/spectral/src/index.ts
- packages/spectral/src/invoke-testing.test.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/testing.ts
- packages/spectral/src/types/DataSourceDefinition.ts
- packages/spectral/src/types/DataSourcePerformFunction.ts
- packages/spectral/src/types/DataSourceResult.ts
- packages/spectral/src/types/Inputs.ts
- Attempted to improve types
- Clarify meaning of data source type vs perform return type
Would appreciate a review when you get a chance @bkegley
> Data Sources

- packages/spectral/package.json
- packages/spectral/src/types/Inputs.ts
- yarn.lock
This provides better typing for JSON Forms schema and UI schema, to provide component developers more direction on what fields are needed. It also removes an unnecessary `data` property.
> Strongly type JSON Forms schema and UI schema

- packages/spectral/package.json
- packages/spectral/src/types-tests/Inputs.test-d.ts
- packages/spectral/src/types/Inputs.ts
> Allow result of clean functions to be null or undefined.

- packages/spectral/package.json
- packages/spectral/src/conditionalLogic/index.test.ts
- packages/spectral/src/conditionalLogic/index.ts
- packages/spectral/src/conditionalLogic/types.ts
- yarn.lock
First commit is the initial port and the second commit contains the modernization for typescript/eslint compliance and using date-fns instead of dayjs.
> Add conditional-logic into spectral

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convert.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/types/TriggerDefinition.ts
- packages/spectral/src/types/TriggerEventFunction.ts
- packages/spectral/src/types/index.ts
- yarn.lock
Minimal scaffolding for previewing Trigger Event Handlers.
> Preview Trigger Event Handlers

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convert.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/types/IntegrationDefinition.ts
- Adjust a few types
- Add icon support
> Code Native Integrations Preview 3

- packages/spectral/package.json
- packages/spectral/src/testing.ts
- packages/spectral/src/types-tests/IntegrationDefinition.test-d.ts
- packages/spectral/src/types/IntegrationAttributes.ts
- Also add a test for the IntegrationDefinition type
> Add external version to IntegrationAttributes

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/flow/templates/flow.ts
- packages/generator-spectral/src/generators/integration/index.ts
- packages/generator-spectral/src/generators/integration/templates/basic.ts
- packages/generator-spectral/src/generators/integration/templates/oauth.ts
- packages/generator-spectral/src/generators/integration/templates/src/index.test.ts
- packages/generator-spectral/src/generators/integration/templates/src/index.ts
- packages/spectral/package.json
- packages/spectral/src/index.ts
- packages/spectral/src/serverTypes/convert.ts
- packages/spectral/src/testing.ts
- packages/spectral/src/types-tests/IntegrationDefinition.test-d.ts
- packages/spectral/src/types/IntegrationDefinition.ts
- yarn.lock
- Streamlined flow triggers and actions a bit
- Fixed a couple bugs in server type conversion
> CNI Preview

- packages/spectral/package.json
- packages/spectral/src/index.ts
- packages/spectral/src/serverTypes/convert.ts
- packages/spectral/src/types/IntegrationDefinition.ts
- yarn.lock
- Use default value for connection inputs as input value if present
- Remove flow name from step names
- Fix up a few references to flow names
- Remove types for references to other components' triggers, connections, data sources, etc.
> More CNI Fixes

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/flow/index.ts
- packages/generator-spectral/src/generators/flow/templates/flow.ts
- packages/generator-spectral/src/generators/integration/index.ts
- packages/generator-spectral/src/generators/integration/templates/basic.ts
- packages/generator-spectral/src/generators/integration/templates/oauth.ts
- packages/spectral/package.json
- packages/spectral/src/serverTypes/convert.ts
- packages/spectral/src/types-tests/IntegrationDefinition.test-d.ts
- packages/spectral/src/types/IntegrationDefinition.ts
- yarn.lock
> CNI Enhancements

- packages/spectral-test/src/testData.test-d.ts
- packages/spectral/src/generators/componentManifest/createStaticFiles.ts
- packages/spectral/src/generators/componentManifest/templates/index.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/package.json.ejs
Add signature to the component manifest package.json.
> Add signature component manifest package.json 

- packages/spectral/src/generators/componentManifest/cli.ts
- packages/spectral/src/generators/componentManifest/createActions.ts
- packages/spectral/src/generators/componentManifest/createConnections.ts
- packages/spectral/src/generators/componentManifest/createDataSources.ts
- packages/spectral/src/generators/componentManifest/createStaticFiles.ts
- packages/spectral/src/generators/componentManifest/createTriggers.ts
- packages/spectral/src/generators/componentManifest/index.ts
- packages/spectral/src/generators/componentManifest/removeComponentManifest.ts
- packages/spectral/src/generators/componentManifest/templates/actions/action.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/connections/connection.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/dataSources/dataSource.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/triggers/trigger.ts.ejs
- packages/spectral/src/generators/utils/createTemplate.ts
- Update component validation to only check for `key, display, or actions`
- Add verbose flag 
- Add checks to for actions, triggers, connections, and datasources before iteration.
> Component Manifest - Validation, Verbose, and etc

- packages/spectral/src/generators/componentManifest/templates/package.json.ejs
- packages/spectral/src/generators/componentManifest/templates/tsconfig.json.ejs
- packages/spectral/src/index.ts
Adds componentManifests function to be consumed by prism generation
> Add component manifests

- packages/spectral/src/generators/utils/getComponentSignatureWithPrism.ts
Change signature check to exec from execFile for windows compatibility.
> CNI - Signature Check Windows Compatibility 

- packages/spectral/src/generators/utils/getComponentSignatureWithPrism.ts
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/IntegrationDefinition.ts
Add visibility and permissions feature for Config Vars & Inputs.
> CNI - Visibility and Permissions for Config Vars & Inputs

- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/IntegrationDefinition.ts
This exposes another interface `IntegrationDefinitionUserLevelConfigPages` that expects to be augmented via the special root export `userLevelConfigPages`. Config variable types (in e.g. `ActionContext['configVars']`) do not widen to `{[key: string]: ConfigVar}` unless _both_ `configPages` and `userLevelConfigPages` aren't exported from the root.
> Add ULC support for CNI

- packages/spectral/src/generators/componentManifest/cli.ts
- packages/spectral/src/generators/componentManifest/createActions.ts
- packages/spectral/src/generators/componentManifest/createConnections.ts
- packages/spectral/src/generators/componentManifest/createDataSources.ts
- packages/spectral/src/generators/componentManifest/createStaticFiles.ts
- packages/spectral/src/generators/componentManifest/createTriggers.ts
- packages/spectral/src/generators/componentManifest/getImports.ts
- packages/spectral/src/generators/componentManifest/getInputs.ts
- packages/spectral/src/generators/componentManifest/index.ts
- packages/spectral/src/generators/componentManifest/templates/connections/connection.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/partials/inputs.ejs
- packages/spectral/src/generators/utils/createDependencyImports.ts
- [CNI - Allow --help at anytime](https://github.com/prismatic-io/spectral/commit/373f99e0d71ffc17d7c5e9c56786cb1d8f9c14bf)
- [CNI - OnPremiseAvailable and OnPremiseControlled pass through](https://github.com/prismatic-io/spectral/commit/a0f2b038f415b33e943291363ddf5e338e1a0c50)
- [CNI - Remove the need for -- from command](https://github.com/prismatic-io/spectral/pull/231/commits/a4cd2819495b344b6eeb8e236f56695364054d90)
- [CNI - Advance doc block controls](https://github.com/prismatic-io/spectral/commit/c8e4d8623422342dc973de8d16c56ac7ba690175)
e.g.
> CNI - OnPremiseAvailable, Help, remove --, and advance doc block controls

- packages/spectral/src/types/Inputs.ts
> CNI - On Prem Connectin intersection ordering for correct warning

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/IntegrationDefinition.ts
- yarn.lock
This allows providing an `instanceProfile` to a CNI definition by providing the stable key of the instance profile:
```ts
const definitionWithInstanceProfile = integration({
name: "Code Native Integration w/ Instance Profile",
version: "0.0.1",
instanceProfile: "custom-instance-profile",
flows: [
// ...
],
});
```
> Add ability to define an instance profile for CNI

- .tool-versions
This updates internal tools used to maintain the Spectral SDK.
> Update Node.js, Yarn, and GitHub CLI tool versions
