- package.json
- src/util.test.ts
- src/util.ts
Would this do the trick to allow component authors to handle `unknown` inputs better?
> Expand type coercion and allow for default values to be specified for util functions

- package.json
- src/index.ts
- src/types/ActionDefinition.ts
- src/util.ts
Define an action key once: in the `actions:` parameter of `component()`.
This removes the need to include the action key as a parameter of `action()`, which could cause problems as the key in `component({actions: {}})` might not match the key defined in `action({key: ""})`. Remove redundancy and make things less error-prone.
I tested this with a component that had a few actions; the component compiles the way it used to without the `key` property of `action()`.
> Remove key property from action()

- package.json
- src/util.test.ts
- src/util.ts
Reasoning: `Boolean('') === false`, so `toBool('')` should probably also return `false` (rather than its current behavior of throwing an error.
For `toInt()`, I'd expect empty string to behave the same as `undefined`.
> Account for empty strings in toBool() and toInt()

- .gitignore
- src/index.ts
- src/types/server-types.ts
Component versioning is now handled by the platform, so the component `version:` key doesn't do anything.  This deprecates the key, and we can remove it entirely once the Prismatic backend schema validator stops expecting the `version` key.
> Deprecate component version key

- package.json
- src/types/ActionDefinition.ts
- src/types/server-types.ts
This removes the component level authorization block in favor of adding it to each action to allow each to specify their own configuration. This includes a major version bump since this completely removes the component authorization block.
> Move authorization config from component to action

- package.json
- src/util.test.ts
- src/util.ts
Recent feedback showed that `isData` and `toData` are not very clear over their purpose. I opted to extend the name to be more verbose and hopefully more clear: `isBufferDataPayload` and `toBufferDataPayload`. I'm definitely open to alternatives on the naming as well. I left the old names in and marked them as deprecated.
> Rename isData/toData to improve clarity on their purpose

- src/types/conditional-logic.ts
Currently we can only mirror these types by hard coding them. Until we decide to publish conditional logic spectral cant depend on it.
> Copied over the updated types from conditonal-logic to spectral

- package.json
- src/types/index.ts
- src/types/server-types.ts
Not sure if this is the best way to export these or not. We want to avoid collisions with existing templated types, which are named the same thing. So this ends up getting used like:
```
import { serverTypes } from "@prismatic-io/spectral";
...
const foo: serverTypes.InputFieldType = "string"; // contrived example
```
Is that what we want?
> Export some useful non-templated types

- package.json
- src/testing.ts
- src/types/TriggerPayload.ts
This will allow integration builders to reference a flow's API key by referencing the output of a trigger (similar to how you can reference a webhookUrl).
> Add webhook API keys to trigger payload

- package.json
- src/testing.ts
- src/types/TriggerPayload.ts
webhookApiKeys should allow for `string[]` instead of just `string`.
> A flow can have multiple API keys

- package.json
- src/index.ts
- src/types/InputFieldType.ts
- src/types/Inputs.ts
- src/types/server-types.ts
Conditional and Connection will require more elaborate defaulting - those
will work as before. The rest have reasonable defaults to be used in the
event the component author left it unspecified.
> Add reasonable defaults for primitive fields

- package.json
- src/index.ts
- src/types/Inputs.ts
- src/types/server-types.ts
`label` can now accept either a `string`, as before, or a more complex
object of `{key: string; value: string}` to allow defining labels for
both labels in `keyvaluelist` collection inputs.
`key` is only passed on to the server if `collection` is set to `keyvaluelist`
though it will accept both forms - `key` is dropped at submission-time.
> Allow specifying a separate label for Key in keyvaluelist inputs

- packages/eslint-config-spectral/package.json
- packages/spectral/package.json
`yarn publish` assumes scoped packages are private unless they already
exist. Adding this section explicitly states that they are indeed scoped and
intended to be public in the NPM registry.
> Add explicit publishConfig package.json sections

- .github/workflows/test.yaml
- packages/spectral/package.json
- packages/spectral/src/serverTypes/convert.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/testing.test.ts
- packages/spectral/src/testing.ts
- packages/spectral/src/types-tests/ComponentDefinition.test-d.ts
- packages/spectral/src/types/ComponentDefinition.ts
- turbo.json
This wraps a Component definition and allows testing a Component by executing
its actions and triggers in a more realistic fashion compared to the old
more direct `invoke` and `invokeTrigger` testing functions.
> Add component testing harness

- packages/spectral/package.json
- packages/spectral/src/clients/http/index.ts
This ends up having implications on the headers supplied to the raw request
client so we need to ensure we only have a FormData instance when we intend
to use form data serialization.
> Avoid falling back to FormData in HTTP client Raw Request

- .github/workflows/test.yaml
- packages/spectral/package.json
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/testing.ts
- packages/spectral/src/types/ActionPerformFunction.ts
This PR adds additional metadata about an instance execution to the `context` paramater, for use by an action or trigger's `perform` function, and will be especially handy for developing actions that configure and remove webhooks in third-party apps.
- `webhookUrls` contains the URLs of the running instance's sibling flows.
- `webhookApiKeys` contains the API keys of the running instance's sibling flows.
- `invokeUrl` was the URL used to invoke the integration.
- `customer` is an object containing an `id`, `name`, and `externalId` of the customer the instance is assigned to.
- `instance` is an object containing an `id` and `name` of the running instance.
> Add additional parameters to context

- packages/generator-spectral/package.json
- yarn.lock
Dependabot identified a half-dozen NPM packages with outstanding CVEs and newer versions that address those CVEs. Nothing super-concerning or critical, but probably good to stay on top of them. All tests still pass with these upgrades.
> Address various dependabot alerts

- packages/generator-spectral/package.json
- packages/spectral/package.json
- packages/spectral/src/util.test.ts
- packages/spectral/src/util.ts
Adds validation for `string`, `schedule` and `picklist` action return types.
> Add additional validition for action return types

- packages/generator-spectral/package.json
- packages/spectral/package.json
- packages/spectral/src/harness-testing.test.ts
- packages/spectral/src/testing.ts
Supports both defaulted values and running unspecified values through
clean functions, if defined. Mimics in-app defaulting behavior as
closely as possible.
> Default inputs in test harness

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/formats/index.ts
- packages/generator-spectral/src/generators/formats/readers/openapi/actions.ts
- packages/generator-spectral/src/generators/formats/readers/openapi/inputs.ts
- packages/generator-spectral/src/generators/formats/utils.ts
- packages/generator-spectral/src/generators/formats/writer/actions.ts
- packages/generator-spectral/src/generators/formats/writer/connections.ts
- packages/generator-spectral/src/generators/formats/writer/index.ts
- Wrap all input data objects in the `input` function to aid in perform fn typing
- Copy in the OpenAPI spec used for component generation
- Fix number/boolean inputs incorrectly using undefined for falsey values
- Escape double quotes in input comments
- Generated components now have a proper jest config
- Generated components also have a minimal start of a harness-based testing file templated out
> OpenAPI generator enhancements

- packages/spectral/src/util.ts
`util.docs.formatJsonExample` was only really useful for internal Prismatic component documentation for built-in components, and we've moved all of those to use `type: "code", language: "json"` for proper syntax highlighting. I think we can safely remove this utility function.
> Remove util.docs.formatJsonExample

- packages/generator-spectral/package.json
- packages/spectral/package.json
- packages/spectral/src/util.test.ts
- packages/spectral/src/util.ts
When an input is a complex data structure, sometimes you don't know if the input you receive will be JSON-serialized or not.
This new utility function, `util.types.toObject()`, detects and parses JSON if it is passed JSON. Else, it returns the object that it received. That way, component users can input static JSON-serialized objects, or they can reference JavaScript objects from previous steps.
> Add toObject util function to easily turn JSON into a parsed object

- packages/spectral/package.json
- yarn.lock
https://nvd.nist.gov/vuln/detail/CVE-2022-39299
I pulled these changes into our [soap component](https://prismatic.io/docs/components/soap/) and verified that it continued to work as expected.
> Address CVE-2022-39299

- packages/generator-spectral/package.json
- packages/spectral/package.json
- packages/spectral/src/types/ComponentDefinition.ts
Our current `component()` definition requires public components to contain a `documentationUrl`, mostly so we remember to include one internally. It omits `documentationUrl` from private components, though. But, it's handy as a private component developer to have a `documentationUrl`, so they can link to docs from the UI easily. This adds `documentationUrl` as an _optional_ property for private components.
> Allow private components to have an optional documentationUrl

- packages/spectral/package.json
- packages/spectral/src/util.test.ts
- packages/spectral/src/util.ts
- yarn.lock
`util.types.toNumber(null, 10)` currently returns `0` because in JavaScript `Number(null)` is `0`. The same is true for `""`, though weirdly not `undefined` (`Number(undefined)` is `NaN`).
This changes the behavior of `util.types.toNumber()` such that when presented `null` or `undefined`, it returns the default value when a default value is presented. Otherwise, it still returns `0`.
> toNumber should use defaults when presented null or empty string.

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/component/index.ts
Some users report errors when building custom components on Windows machines running NodeJS version 18+ (the latest LTS). 
```
PS C:\Users\Administrator\my-component> npm run build
> my-component@0.0.1 build
> webpack
C:\Users\Administrator\my-component\node_modules\loader-runner\lib\LoaderRunner.js:146
if(isError) throw e;
^
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
at BulkUpdateDecorator.hashFactory (C:\Users\Administrator\my-component\node_modules\webpack\lib\util\createHash.js:145:18)
at BulkUpdateDecorator.update (C:\Users\Administrator\my-component\node_modules\webpack\lib\util\createHash.js:46:50)
at RawSource.updateHash …
```
> Bump webpack to latest to address compat issue with NodeJS 18+

- packages/generator-spectral/package.json
- packages/spectral/package.json
- yarn.lock
`qs` was a downstream dependency of `soap`, and had a [CVE](https://github.com/prismatic-io/spectral/security/dependabot/23). This bumps `soap` to latest, and latest `soap` does not have `qs` as a dependency.
I verified that components generated via `prism` with this change are identical to those generated by an older version.
> Address CVE in qs package

- packages/spectral/src/types/Inputs.ts
`data` will be used to supply default values to the inputs in a form.
> Re-add data property to JSON Form results

- packages/spectral/package.json
- packages/spectral/src/clients/http/index.ts
When a raw request action makes a request to an HTTP endpoint, but does not have a payload, `payload` is an empty string, `""`, which axios apparently serializes into `"\"\""`. That's usually fine -- you either specify a real payload, or you are doing a GET or DELETE request, and the HTTP body is ignored by the server. 
_However_, some APIs (looking at you, Shopify) will reject a GET or DELETE request if it contains any body in the request.
If the payload is an empty string, this causes the request to actually send nothing (and not the two-character `""` as the body).
> Fix blank data payloads for raw request actions

- packages/spectral/package.json
- packages/spectral/src/testing.ts
Most connections contain all of their data in `.fields`. OAuth connections have additional data in `.token`. This allows you to create a connection with `.token` populated. For example,
```
const sfConnection = createConnection(
salesforceOAuth,
{},
{
instance_url: "https://example.my.salesforce.com",
access_token: "abc-123",
}
);
```
> Allow createConnection to contain tokens, so you can test OAuth connections

- package.json
- yarn.lock
Dependabot flagged a few non-critical CVEs in down-stream _dev_ dependencies from the `yo` project (which is used for generating new components). Newer, patched versions of the down-stream dependencies are available, but the `yo` project has not updated to the latest patched versions. This PR forces updates for the various patched packages. I tested each update of a down-stream dependency and verified that it does not break any functionality. With these updates, you can still initialize and build custom components with `prism`.
> Address existing CVEs from Dependabot

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/component/index.ts
When initializing a new component, NPM throws a warning that webpack version 5.75.0 and below has an active CVE. This bumps webpack to current latest.
> Bump the version of webpack that is templated for new components

- packages/spectral/package.json
- packages/spectral/src/clients/http/index.ts
- packages/spectral/src/util.ts
Spectral's HTTP client is used to generate "Raw Request" actions for many components. It includes a "File Data" input, where users can provide file names and contents to upload as part of a multi-part form POST.
The HTTP client does _not_ currently handle binary files https://prismatic.io/docs/custom-components/writing-custom-components/#handling-binary-files-in-custom-components . Binary files (images, PDFs, mp3s, etc) are passed between steps as objects of the form `{data: Buffer, contentType: string}`. Currently, if you reference one of these objects in a Raw Request action, you get a cryptic error because axios doesn't understand the object format. 
This change will take an input, and if it is already `{data: Buffer, contentType: string}`, will keep it in that form, and if it is a …
> Handle binary files better in raw request actions

- packages/spectral/package.json
- packages/spectral/src/clients/http/index.ts
- packages/spectral/src/clients/http/inputs.ts
When you include a file in a form-data POST or PUT request, that file can include a `filename`. That `filename` is often used by a third-party API to determine MIME type, present the file in their app, etc.
Up until now, the `filename` was always set to the file's `key`. That resulted, in many apps, in a file simply named `file`.
This allows you to optionally specify a name for a file that you're uploading.
> Add an input for form data file names

- packages/spectral/package.json
- packages/spectral/src/types/ConnectionDefinition.ts
This will allow a component developer to enable the [PKCE extension](https://oauth.net/2/pkce/) for the OAuth 2.0 Authorization Code flow. When enabled, users who complete the OAuth 2.0 auth code flow will bring a `code_challenge` to the third-party when authenticating. When an authorization code is exchanged for an access token, the third-party will be presented a corresponding `code_verifier`.
> Add PKCE support to OAuth 2.0 Authorization Code flow

- packages/spectral/package.json
- packages/spectral/src/conditionalLogic/index.test.ts
- packages/spectral/src/conditionalLogic/index.ts
- packages/spectral/src/util.ts
- yarn.lock
The library that we use for datatime comparison, `date-fns`, dropped support for string dates (like `2023-05-23`) in v2.0.0. This PR expands our support for various timestamp formats. We can now compare `Date()` objects, ISO strings (like `"2030-03-20T12:50:30.105Z"`), or Unix epoch timestamps (like `1631568050` or its string equivalent).
> Add Unix epoch support for util.types.toDate() and support string dates for comparison operators

- package.json
- packages/generator-spectral/jest.config.ts
- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/formats/readers/openapi/actions.ts
- packages/generator-spectral/src/generators/formats/readers/openapi/util.test.ts
- packages/generator-spectral/src/generators/formats/readers/openapi/util.ts
- turbo.json
Variables cannot start with numbers so convert those to text, similar to what was done for the "action groups" (filenames).
> Handle operationIds with leading numbers

- packages/spectral/package.json
- packages/spectral/src/util.test.ts
- packages/spectral/src/util.ts
`isBufferDataPayload` was misidentifying objects of the form 
```
{
"data" : {
"foo": "bar"
}
}
```
as `DataPayload` objects because they are an object with a `data` property.
But, the check is missing a critical piece: the `data` property needs to be a `Buffer`. This change checks that the object's `data` property is a `Buffer`.
> isBufferDataPayload should return true only if the data property is a Buffer

- packages/spectral/package.json
- packages/spectral/src/types/Inputs.ts
Inputs with `type: "code"` default to using `javascript` syntax highlighting when no `language` is specified. Code inputs are rarely JavaScript, though, and more commonly `graphql`, `sql`, `xml`, `html`, etc. This change requires a user to specify syntax highlighting language when an input of `type: "code"` is used, and includes the languages we support syntax highlighting for. Users can specify `plaintext` to indicate that they do not want syntax highlighting.
> Require langauge for syntax highlighting for code inputs

- packages/spectral/package.json
- packages/spectral/src/index.ts
- packages/spectral/src/serverTypes/convert.ts
- packages/spectral/src/types-tests/ComponentDefinition.test-d.ts
- packages/spectral/src/types/ComponentDefinition.ts
Mostly an internal-focused update. All of our public components have documentation links of the form `https://prismatic.io/docs/components/KEY`. We should put up guard rails to ensure new public components all have correct documentation URLs.
> Ensure correct docs links for public components

- package.json
- packages/spectral/package.json
- packages/spectral/src/conditionalLogic/index.test.ts
- packages/spectral/src/conditionalLogic/index.ts
- yarn.lock
Suppose you have an integration that might receive an array as part of its body. You want to create branching logic to say: `if this array is included in the payload, and if "foo" is included in the array, follow this branch`. You could add branching logic that looks like this:
The JavaScript equivalent to this branch logic would be something like `if ( payload?.myArray && myArray.includes("foo") ) { doThing(); }`
That doesn't currently work with the way we process predicates. We currently evaluate all predicates (the "if this array exists" and "if this array contains 'foo'") at once, and then `reduce` the result. In this case, if an array doesn't exist the branch step will throw an error about the non-existent array not being an array - `Execution of 'Branch on Expression' failed with …
> Evaluate conditional predicates from left to right like JavaScript, rather than all at once

- packages/spectral/package.json
- packages/spectral/src/testing.ts
This adds functionality to test trigger `onInstanceDeploy` and `onInstanceDelete` functions in a unit test.
> Add test harness functions to test trigger onInstanceDeploy and onInstanceDelete functions

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/formats/readers/openapi/inputs.ts
An object can be defined in an OpenAPI spec with properties that are `readOnly`. It's handy to be able to reference that same object for a `requestBody` and for a return value (to prevent having to maintain two versions of the same object). But, we're currently templating out inputs for `readOnly` properties. We should filter out the `readOnly` properties as we generate inputs.
> Do not template inputs for readOnly properties in OpenAPI-generate components

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/component/index.ts
Version 27.0.x of Jest has some deficiencies when processing ECMAScript modules that is solved in more recent versions. This bumps the default version of Jest that is installed when a new custom component is initialized.
> Bump default Jest version for custom components

- packages/spectral/package.json
- packages/spectral/src/harness-testing.test.ts
- packages/spectral/src/types-tests/ExtractValue.test-d.ts
- packages/spectral/src/types/ActionInputParameters.ts
- packages/spectral/src/types/Inputs.ts
This PR focuses on two goals:
- The type of `default` is now known statically for all InputFields.
- The types of the `collection` and `default` properties are correctly coupled.
Other notes:
- `DataInputField` uses `Buffer` as its generic type instead of `string` like the other inputs.
- The `clean` functions remain the type `InputCleanFunction<unknown(, unknown)>`.
> More strictly define collection/default type combinations for different InputFields

- packages/generator-spectral/package.json
- packages/spectral/package.json
- packages/spectral/src/index.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/types-tests/ConnectionDefinition.test-d.ts
- packages/spectral/src/types/ConnectionDefinition.ts
Adds `onPremiseConfig` optional metadata to enable on prem variants of connections. One shortcoming of the currently implementation is that the `replacesInputs` type doesn't have enough type inference to restrict it's array members to the keys of the `inputs` field. An attempt to address that exists on branch `rm/sc-18076/onprem-connections-generics` but it has tradeoffs.
> On Premise Connection Configuration

- packages/eslint-config-spectral/package.json
- packages/eslint-config-spectral/src/index.ts
When generating a component from an OpenAPI spec, some action files will include an import of `util` from `@prismatic-io/spectral`, but will not use `util` in inputs. Running a subsequent `npm run format` of the generated project, then, yields `@typescript-eslint/no-unused-vars` errors. This downgrades those errors to warnings so the format can continue to run.
> Add no-unused-vars rule to eslint

- packages/generator-spectral/package.json
- packages/generator-spectral/src/generators/formats/index.ts
- packages/generator-spectral/src/generators/integration/index.ts
Similar to #171, this bumps the default version of Jest that is templated when a code-native integration is initialized. This is needed, as a more recent version of Jest is required for compatibility with the latest `axios` library.
> Bump default Jest version for newly initialized code-native integrations

- packages/spectral/package.json
- packages/spectral/src/clients/http/index.ts
- packages/spectral/src/util.test.ts
- packages/spectral/src/util.ts
- yarn.lock
Currently, if you select `debug: true` in a `createClient` function, you can run out of memory if you request sufficiently large binary files (i.e. a several MB PDF file). This is due to the JSON serialization of the PDF file's `Buffer`.
This PR simplifies or extends a few things:
1. When `debug: true` is enabled for an HTTP client, extraneous properties of `request` and `response` are no longer logged. Axios provides lots of metadata about the request (like `maxFreeSockets` that simply aren't helpful when debugging a request in Prismatic. Relevant properties, like base URL, url, HTTP method, headers, status code and payload are retained. 
2. When a payload is "large" (> 10KB) or when it's a binary file (represented as a `Buffer`), the data will be represented as `<data (10000000 …
> Simplify http debug logging

- packages/spectral/src/util.test.ts
- packages/spectral/src/util.ts
When sending payloads via HTTP client to an API, many paramaters are optional and we end up needing a series of spread operators when constructing the request payload. For example,
```
const body: CreateListBody = {
name,
...(content && content.length && { content }),
...(dueDate !== undefined && { due_date: dueDate }),
due_date_time: dueDateTime,
...(priority !== undefined && { priority }),
...(assigneeInt !== undefined && { assignee: assigneeInt }),
...(status && status.length && { status }),
};
```
This could be simplified with the new `cleanObject` function:
```
const body: CreateListBody = util.types.cleanObject({
name,
content,
due_date: dueDate,
due_date_time: dueDateTime,
priority,
assignee: assigneeInt,
status
})
``` 
The `cleanObject` function defaults to removing properties …
> Add cleanObject util function

- packages/spectral/package.json
- packages/spectral/src/clients/http/index.ts
When an error is thrown by Axios, it's handy to have access to the HTTP status and response headers returned from the API, without needing to parse the HTTP status code from the error message.
This makes it so when HTTP responses are caught by the generic HTTP client's `handleErrors` function, the response's status code and headers are included alongside the response's data in the error that is yielded. 
That'll make [step-level error handling](https://prismatic.io/docs/building-integrations/#step-error-handling) easier.
> Add HTTP status code and response headers to error handler

- packages/spectral/src/types/ActionPerformFunction.ts
- packages/spectral/src/types/DataSourcePerformFunction.ts
This eases direct usage of the types, particularly in contexts where type inference won't be able to determine a more specific type.
> Default ActionContext/DataSourceContext config var generics

- packages/spectral/package.json
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/types/ActionPerformReturn.ts
When invoking a flow synchronously, you can return a response body, content type and HTTP status code to the caller from the last step of the integration. With an upcoming change, you'll also be able to return custom headers. This will be helpful when responding with redirects, etc.
> Return custom headers from an action in a synchronous request

- packages/spectral/package.json
- packages/spectral/src/conditionalLogic/index.test.ts
- packages/spectral/src/conditionalLogic/index.ts
The `contains` function is designed to determine if an element is contained within an array (or object, or string... but this PR relates to arrays).
For strings, it works as expected - `"foo"` is contained in `["foo", "bar"]`.
For numbers, it works as expected - `2` is contained in `[1,2,3]`.
For stringified numbers, it does not work as expected. It currently returns `false` if you check if `"2"` is contained in `["1", "2", "3"]`.
That's because the element you check is passed through the `parseValue` function, which checks if the value is a string and, if so, the value is `JSON.parse`'d. `JSON.parse("2")` becomes `2`, and `2 !== "2"`.
This PR loosens restrictions on contains, so that the value `"2"` would be passed to `contains`, and both the values `"2"` and `2` would be searched for in …
> Fix the contains function to handle stringified numbers

- packages/spectral/src/types/Inputs.ts
A JSON form can yield an object (`Record<string, unknown>`) or it can return an array if the schema has a top-level array declared (like this example https://prismatic.io/docs/jsonforms/playground/?key=basic-array). 
Our TypeScript should allow for both.
> JSON Forms data results can be arrays in addition to key/value objects

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/serverTypes/integration.ts
- packages/spectral/src/types/IntegrationDefinition.ts
When building a code-native integration, you may want to reference an existing connection template https://prismatic.io/docs/connections/#connection-templates. This change allows you to specify a `template` by name when you reference an existing component's connection.
> Add connection templates to code-native reference connections

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types-tests/ConfigVars.test-d.ts
- packages/spectral/src/types/DataSourceResult.ts
- packages/spectral/src/types/IntegrationDefinition.ts
This better aligns CNI `collectionType` configuration with the Designer's; no `collectionType` for schedule or connection `dataType`s or for a few types of data sources.
> Refine collection type handling for CNI config vars

- packages/spectral/.eslintignore
- packages/spectral/bin/component-manifest.js
- packages/spectral/package.json
- packages/spectral/src/generators/componentManifest/cli.ts
**Issue:**
Our `bin` executables currently reference the **tsc** compiled `cli.ts -> cli.js` file. However, Typescript does not maintain the files' runtime permissions and resets them to the least amount of privileges. 
The configuration for this is:
```
"bin": {
"component-manifest": "./dist/generators/componentManifest/cli.js"
},
```
To work around this, we introduced an npm script that runs after the build process to provide the generated `cli.js` file with its executable permission. However, the issue with this is it's not cross-platform compatible.
**Solution:**
Instead, we'll have a static `bin` directory as a sibling to the `src` and `dist` folders. This `bin` directory will need to be published along with Spectral. This `bin` folder will contain executable files that reference …
> Make Bin executables Cross Platform compatible

- packages/spectral/package.json
This means that you should only include the EJS template files in the 'build:template' script during the build process. This will help prevent the unnecessary copying of files that are not needed for the final build, which can help optimize the build process and reduce the size of the final output.
> Only include the EJS (Embedded JavaScript) templates in the 'build:template' script to prevent unnecessary file copies.

- packages/spectral/src/generators/componentManifest/templates/package.json.ejs
- packages/spectral/src/generators/utils/getComponentSignatureWithPrism.ts
- Since we're generating the signature differently (process.stdout.write to oclif this.log) this needs to be updated.
- Window cross platform script update
> CNI - Signature Validation & Package Script Compatible Command

- packages/spectral/src/generators/componentManifest/cli.ts
- packages/spectral/src/generators/componentManifest/index.ts
- packages/spectral/src/generators/utils/createFlagHelpText.ts
- packages/spectral/src/generators/utils/getComponentSignatureWithPrism.ts
- Add flag `--skip-signature-verify` to allow uses to always create a signature in the component manifest, whether the component has been published or not to the platform.  
- Update the package name default to `@component-manifests/[component-key]` instead of `@components/[component-key]-manifest`
> CNI - Skip signature verification & update package name default

- packages/spectral/src/generators/componentManifest/removeComponentManifest.ts
The 'fs-extra.remove' function didn't remove the previous manifest. Replacing it with 'rmSync' fixed the issue. The problem was likely caused by the presence of files and subdirectories, which prevented the function from removing everything altogether.
> CNI - Fix Cleanup Bug

- packages/spectral/src/generators/componentManifest/templates/partials/inputs.ejs
- packages/spectral/src/types/ComponentManifest.ts
For any of the properties in the `inputs` object of a manifest function we need to cast `as const` so the specific value carries through for use in spectral's types.
> Fix generated input types in component manifests

- packages/spectral/src/generators/componentManifest/cli.ts
- packages/spectral/src/generators/componentManifest/getInputs.ts
- Shown inputs with the value `false` need to be removed from perform interface and inputs declaration. 
- Inputs with a default value should always be optional, even if required is `true`.
- Fix package name format issue, capitalize letters in package name are invalid and throws a warning.
> CNI - Input default, shown functionality and package name updates.

- packages/spectral/src/types/Inputs.ts
Reorder the type intersections to correctly infer types. 
Issue:
Now we get (which is correct):
> Input Type - Inference issue with collection types

- packages/spectral/src/generators/componentManifest/templates/actions/action.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/connections/connection.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/dataSources/dataSource.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/partials/performArgs.ejs
- packages/spectral/src/generators/componentManifest/templates/triggers/trigger.ts.ejs
For CNI Action Calling, add additional un-escaping to EJS Templating.
> CNI - Unescape additional EJS docs

- packages/spectral/src/generators/componentManifest/createStaticFiles.ts
some older components don't have these properties and so were failing generation. this adds the `??` to account for this
> Adds Nullish to Account for Older Components

- packages/spectral/package.json
- packages/spectral/src/generators/componentManifest/getInputs.ts
The components that utilize models can employ an arbitrary data type, which can be arrays, objects, or even escaped characters. To properly type this, we need to validate what these data types are and then return the correct corresponding types.
```
SyntaxError: ';' expected. (15:17)
13 |  * @example [{\&#34;con\&#34;: \&#34;asc\&#34;}]
14 |  */
> 15 |   orderBy?: "[{"con": "asc"}]" | "[{"con": "desc"}]" | "[{"lastModified": "asc"}]" | "[{"lastModified": "desc"}]" | "[{"name": "asc"}]" | "[{"name": "desc"}]";
|                 ^
16 |    /**
17 |  * First N Items
18 |  * The number of items to return.
```
```
SyntaxError: Unterminated string literal. (18:18)
16 |  * @placeholder The type of newline to use
17 |  */
> 18 |   newlineType?: "
|                  ^
19 | " | "
20 | ";
21 |    /** …
```
> CNI - Fix Model union types that are objects, arrays, escaped characters

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/serverTypes/integration.ts
To define a valid YAML configuration, we need to hoist the `onPremiseConnectionConfig` on the required configuration variable. in CNI, to satisfy the types correctly we need to be part of the connection variable used for type discrimination.
**CNI:**
```
export const configPages = {
Connections: configPage({
elements: {
test: connectionConfigVar({
stableKey: "b2b377ee-27ce-4f59-b248-b4dafdea93f3",
dataType: "connection",
connection: {
component: "smtp",
key: "smtpConnection",
onPremiseConnectionConfig: "required",
values: {
host: {
value: "eeee",
},
port: {
value: "bbbb",
},
password: {
value: "test",
},
username: {
value: "asdf",
},
},
},
}),
...
```
**YAML Definition:**
```
definitionVersion: 7
isCodeNative: true
name: integration
description: Prism-generated Integration …
```
> CNI - Hoist OnPremConnectionConfig on Required Config Var

- packages/spectral-test/src/testData.test-d.ts
- packages/spectral/package.json
- packages/spectral/src/generators/componentManifest/createActions.ts
- packages/spectral/src/generators/componentManifest/createConnections.ts
- packages/spectral/src/generators/componentManifest/createDataSources.ts
- packages/spectral/src/generators/componentManifest/createTriggers.ts
- packages/spectral/src/generators/componentManifest/helpers.ts
- packages/spectral/src/generators/componentManifest/templates/actions/action.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/actions/index.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/connections/connection.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/connections/index.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/dataSources/dataSource.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/dataSources/index.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/partials/importBarrel.ejs
- packages/spectral/src/generators/componentManifest/templates/partials/inputs.ejs
- packages/spectral/src/generators/componentManifest/templates/partials/performArgs.ejs
- packages/spectral/src/generators/componentManifest/templates/triggers/index.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/triggers/trigger.ts.ejs
- packages/spectral/src/generators/utils/createImport.ts
- packages/spectral/src/generators/utils/createTypeInterface.ts
- packages/spectral/src/generators/utils/formatType.ts
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/ComponentManifest.ts
- packages/spectral/src/types/ComponentRegistry.ts
**DRAFT**
In older legacy components, some did not utilize the `action()`, `connection()`, `dataSource()`, and `trigger()` wrappers. This enabled developers at the time to add the `key` property with arbitrary values, including invalid ones like `computemd5-sha1` and `Smartsheet OAuth2`. Now, we need to convert these to adhere to valid interface and import file naming conventions.
```
SyntaxError: ',' expected. (2:20)
1 | import { oauth } from "./oauth";
> 2 | import { connection-string } from "./connection-string";
SyntaxError: ',' expected. (1:21)
> 1 | import { Smartsheet OAuth2 } from "./Smartsheet OAuth2";
|                     ^
2 | import { apiKey } from "./apiKey";
SyntaxError: ',' expected. (7:20)
5 | import { computemd4 } from "./computemd4";
6 | import { computemd5 } from …
```
> CNI - Update derived type interfaces to format invalid type interfaces names

- packages/spectral/src/generators/componentManifest/cli.ts
When creating the package.json for certain packages like `aws-s3` we incorrectly kebab cased the package.json name. This removes that function from the generation.
assumes that the platform does not allow arbitrary component keys
> removes kebab case and uses component key for package.json name

- packages/spectral/package.json
- packages/spectral/src/types/ConnectionDefinition.ts
Add explicit interface, `OAuth2Config`, to `ConnectionDefinition`. Only applicable to `OAuth2AuthorizationCodeConnectionDefinition`.
> Add OAuth2Config interface to ConnectionDefinition

- packages/spectral-test/src/ComponentReference.test-d.ts
- packages/spectral-test/src/IntegrationDefinition.test-d.ts
- packages/spectral-test/src/testData.test-d.ts
- packages/spectral/src/types/IntegrationDefinition.ts
It's common for developers to want to abstract function calls using existing component actions. Extracting those types from the execution context was pretty difficult and required some inside knowledge about how module augmentation works. This exposes those types for use in these cases.
> Expose FlowExecutionContext types to better support abstracting action calls

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertComponent.ts
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/ComponentRegistry.ts
- packages/spectral/src/types/ConfigVars.ts
- packages/spectral/src/types/ConnectionDefinition.ts
- packages/spectral/src/types/Inputs.ts
Allow users to set the visibility of Config Var Connections inputs, whether it's for reference or definitions config var connections in CNI. Here are the properties you can use: 
- `permissionAndVisibilityType`: Choose from "customer," "embedded," or "organization."
- `visibleToOrgDeployer`: Set this to true or false.
> CNI - Connection Reference/Definition Visibility

- packages/spectral/package.json
- packages/spectral/src/generators/componentManifest/getImports.ts
- packages/spectral/src/generators/componentManifest/getInputs.ts
- Removed the unused `DocBlock` type.
- Consolidated redundant conditionals.
- Resolved issues with import types concerning collections. The problem was that when the input was a collection, we didn’t account for the possibility of it being an external type. Instead, we mistakenly assumed it was a string type, which was incorrect.
> CNI - Resolved issues with import types concerning collections

- packages/spectral-test/src/ConfigVars.test-d.ts
- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/ConfigVars.ts
This change allows users to define a `ValidationMode` for JSON forms via CNI.
This PR:
* Converts `validationMode` definitions into YAML when relevant
* Adds `validationMode` type hinting
* Adds simple type tests
* Bumps `spectral` version
> CNI - Allow ValidationMode definition for JSON forms

- packages/spectral/package.json
- packages/spectral/src/cni-testing.test.ts
- packages/spectral/src/serverTypes/convertIntegration.ts
This PR addresses a CNI issue where including default `keyvaluelist` items as the type hinting described would not build valid YAML. It includes:
* An update to `convertConfigVar` to enable both `keyvaluelist` and `valuelist` config vars to be processed properly
* Basic tests for config var input conversion
> CNI - Bugfix - Default keyvaluelist items not converting to valid YAML

- packages/spectral/package.json
- packages/spectral/src/generators/componentManifest/createActions.ts
- packages/spectral/src/generators/componentManifest/docBlock.ts
- packages/spectral/src/generators/componentManifest/getInputs.ts
- packages/spectral/src/generators/utils/escapeSpecialCharacters.ts
This PR addresses an issue where including `/* doc blocks */` or `` `backticked` `` values in input fields would cause the component manifest generator to fail.
> Component manifests - Escape input strings

- packages/spectral/src/clients/http/index.ts
This adds search parameters to debug log lines when debugging an HTTP request.
> Add search params to debug output

- packages/eslint-config-spectral/package.json
- packages/spectral/package.json
Not bumping Spectral version, since this change is cosmetic and can go out with the next version of Spectral.
> Add code-native integrations to project descriptions

- packages/spectral-test/src/ConnectionDefinition.test-d.ts
- packages/spectral/package.json
- packages/spectral/src/harness-testing.test.ts
- packages/spectral/src/invoke-testing.test.ts
- packages/spectral/src/serverTypes/convertComponent.test.ts
- packages/spectral/src/serverTypes/convertComponent.ts
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/types/ConfigVars.ts
- packages/spectral/src/types/ConnectionDefinition.ts
- packages/spectral/src/types/DisplayDefinition.ts
This adds support for the new `connectionAvatarIcon`. This allows distinguishing between the icon displayed as the avatar and the icon used for the OAuth connect button.
In order to support this for components and CNI there is a breaking change for connection definitions. `label` and `comment` are now nested in a `display` block to match other definition interfaces. This display block defines `icons` for both avatar icon and oAuthConnectionButton icon.
> Add support for connection avatar icons

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/ConnectionDefinition.ts
This change adds the ability to configure custom redirect URI's on connectionConfigVars using either connectionDefinitions or prebuilt connections.
> CNI: Support custom OAuth2 URI redirects on connections

- packages/spectral/package.json
- packages/spectral/src/serverTypes/perform.test.ts
- packages/spectral/src/serverTypes/perform.ts
Previous behavior was to iterate over the collection of provided inputs but this meant that certain scenarios, such as version upgrades, wouldn't get an opportunity to run input clean functions if the value wasn't present in the collection of input values.
Now clean functions will be given `undefined` and an opportunity to run and clean the value into something usable/expected.
> Run input clean functions even if value not explicitly provided

- packages/spectral-test/src/PollingTriggerDefinition.test-d.ts
- packages/spectral/package.json
- packages/spectral/src/index.ts
- packages/spectral/src/serverTypes/perform.ts
- packages/spectral/src/types/PollingTriggerDefinition.ts
- packages/spectral/src/types/TriggerResult.ts
Setting this field to `true` will mark the execution as having no results in the backend, thus resulting in filterable logs in the frontend UI.
Other notes:
* Added support for conditional branching in polling triggers (was not intentionally excluded previously)
* Updated types
> Add polledNoChanges field to polling TriggerResults

- packages/spectral/package.json
- packages/spectral/src/generators/componentManifest/getInputs.ts
HubSpot has a datasource with an input that is a `valuelist` with a `model`, defined like this:
```
export const objectsToSelect = input({
label: "Objects to Select",
type: "string",
collection: "valuelist",
model: [
{ label: "Contacts", value: "Contacts" },
{ label: "Companies", value: "Companies" },
{ label: "Deals", value: "Deals" },
{ label: "Tickets", value: "Tickets" },
{ label: "Calls", value: "Calls" },
{ label: "Line Items", value: "Line Items" },
],
required: false,
comments: "The objects to include in the selection list.",
clean: (value: unknown): string[] => {
return util.types.isPicklist(value)
? (value as string[]).map((name) => name.trim())
: [];
},
});
```
Currently, the component manifest generated from this input reads
```
objectsToSelect?: `Contacts` | `Companies` | …
```
> Fix array types for valuelist inputs that have models

- packages/spectral/src/generators/componentManifest/cli.ts
- packages/spectral/src/generators/utils/getSpectralVersion.ts
I had an older version of `component-manifest` installed locally, and couldn't readily identify which version of `@prismatic-io/spectral` it belonged to without digging in to global `node_modules`.
This exposes a `component-manifest --version` flag, which will print the version of `@prismatic-io/spectral` it came from.
> Add --version flag to component-manifest command

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
Currently, if you have a code-native data source config variable with an input that is a `collection: "valuelist"` (like `objectsToSelect` below) we expect a `value` that is an array of strings, like this:
```
"Hubspot Objects": dataSourceConfigVar({
stableKey: "my-hubspot-objects",
dataSource: {
component: "hubspot",
key: "getObjectSelection",
values: {
connection: { configVar: "HubSpot API Key" },
includeCustomObjects: { value: true },
objectsToSelect: { value: ["Companies", "Contacts"] },
},
},
}),
```
That's great and correct, but currently our code-native YAML definition generator generates YAML that reads:
```
objectsToSelect:
type: complex
value:
- Contacts
- Companies
```
That's incorrect. It should read:
```
objectsToSelect:
type: complex
value:
- type: value
value: Companies
- …
```
> Fix YAML definition generation for valuelist inputs of data sources

- packages/spectral/package.json
- packages/spectral/src/serverTypes/perform.ts
By the time inputs make it to an `invokeAction` call in a trigger, they have already been cleaned. Depending on how the clean functions, running clean twice can lead to unwanted behavior here (e.g. the "keyValPairToObject" util expecting an array and returning an object; running it twice causes errors).
> Polling triggers: Clean poll action inputs only once

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/serverTypes/perform.ts
`createDebugContext` wasn't getting called when constructing contexts for triggers and polling actions, causing references to `context.debug` and its contained methods to fail at runtime.
In retrospect maybe this was a good enough reason to consider defining the debug methods in the runner instead, to prevent having to augment the context in so many places in the spectral layer, but for now this will at least fix the problem.
> Make debug context available in polling & trigger executions

- packages/spectral/package.json
- packages/spectral/src/conditionalLogic/index.ts
This PR supports the eventual release of the [YAML > CNI converter tool](https://github.com/prismatic-io/prism/pull/126) in prism.
Currently, the alpha version of the tool converts conditional in this way:
```ts
import { evaluate } from "@prismatic-io/spectral/dist/conditionalLogic";
if (
evaluate([
BooleanOperator.and,
[BinaryOperator.equal, someReference, "some value"],
])
) {
// body here
}
```
While it works, it is pretty unreadable and unnecessarily reveals how we evaluate conditionals. Leaning on the `evaluate` directly function is also something we probably don't want to encourage.
With the introduction of this PR, conditionals can now render like this:
```ts
import { isEqual } from "@prismatic-io/spectral/dist/conditionalLogic";
if (isEqual(someReference, "some value")) {
// body …
```
> Export conditional logic methods to support YAML => CNI converter tool

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertComponent.ts
It's possible for polling triggers to have undefined inputs. This falls back to an empty object in that case.
> Fix component generation with undefined inputs

- packages/spectral/package.json
- yarn.lock
This superseeds #310, #314 and #315.
Our main concern with bumping Axios (#310) was that "Raw Request" actions expect to be able to override base URL in custom components, and a newer version of Axios may change that behavior. I verified that with the latest Axios, you can continue to override base URL as needed from a "Raw Request" action.
#314 and #315 were downstream dependencies of jest and were updated to patched versions, addressing each security flag.
> Bump axios, axios-retry and @babel/*

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/ConfigVars.ts
Previously CNI developers could not define `htmlElement` config vars in their config pages. This change makes it so the typing supports it & that they get converted into proper YAML (i.e. htmlElements should not show in the `requiredConfigVars` block)
> Support htmlElement configVars

- packages/spectral/src/serverTypes/convertComponent.test.ts
- packages/spectral/src/serverTypes/convertComponent.ts
- packages/spectral/src/serverTypes/index.ts
- packages/spectral/src/types/Inputs.ts
Component authors may now provide the key of a data source from the component that will be used to provide the value of the input when configuring the action in Prismatic.
> Add ability to define a data source that backs an action input

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/serverTypes/integration.ts
`orgOnly` is no longer a valid property in an integration definition when using a scoped config var
> Fix CNI generation when using new connection types

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- biome.jsonc
- package.json
Without a .vscode directory, my VS Code's prettier and biome plugins fight with one another over formatting. This explicitly declares that biome is the formatter for this project (which it already is).
> Add .vscode directory

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
This PR supports adding build/import-specific metadata to generated CNI.
This should not be merged until the definition schemas are updated in the backend.
> Support importMetadata

- packages/spectral/package.json
- packages/spectral/src/types/ConfigVars.ts
- packages/spectral/src/types/Inputs.ts
- packages/spectral/src/types/jsonforms/JsonSchema.ts
- packages/spectral/src/types/jsonforms/UISchemaElement.ts
- packages/spectral/src/types/jsonforms/ValidationMode.ts
- yarn.lock
This removes our dependency on `@jsonforms/core`. We require just a hand-full of types and interfaces from `@jsonforms/core` - this pulls those type definitions into this library.
> Remove dependency on @jsonforms/core

- packages/eslint-config-spectral/LICENSE
- packages/eslint-config-spectral/package.json
- packages/spectral-test/LICENSE
- yarn.lock
Eslint 8.x is EOL, and the version of `@typescript-eslint/eslint-plugin` that we're on (among others) has a peer dependency on 8.x. That prevents a component developer from bumping to eslint 9.x without ignoring peer dependencies. 
This bumps eslint-related packages in `@prismatic-io/eslint-config-spectral` to latest, which are all now have peer dependencies of eslint 8.x || 9.x.
I tested this by initializing a new component, installing eslint 9.x and getting peer dependency errors. Installing this updated package and seeing my peer dependency issues disappear, and reverting eslint to 8.x with this new library to ensure backwards-compat.
Addresses #319
> Bump eslint-related packages to ensure eslint 9 compatibility

- package.json
- packages/spectral/package.json
- packages/spectral/typedoc.json
- yarn.lock
We used to generate docs pages for Spectral, but those weren't terribly useful - it's more useful to have jsdoc strings on each function/property which links to extended documentation with examples of how to use each function/property.
This removes our unused dependency on `typedoc`.
Additionally, we used `resolutions` in `/package.json` to force upgrades of some downstream dependencies with CVEs. These resolutions are no longer necessary, as we've updated the packages that introduced these downstream dependencies, and the vulnerable downstream dependencies are on versions that are patched.
> Remove TypeDoc

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertComponent.test.ts
- packages/spectral/src/serverTypes/convertComponent.ts
This PR adds basic validation for `connectionTemplateInput` template strings. We check that:
* Keys referenced in the template string must be declared as inputs
* Keys referenced in the template do not reference other template inputs
* The template string contains some number of template slots
> Add basic connection template input validation

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
This is similar to #261 .
Suppose you use a component like `ms-sharepoint`, but you don't give the component manifest the key `ms-sharepoint` - you use `sharepoint` or `msSharepoint` instead.
```
import sharepoint from "@component-manifests/ms-sharepoint";
export const componentRegistry = componentManifests({
sharepoint,
});
```
Typescript will allow you to reference a datasource from the Sharepoint component like this
```
"Select Sharepoint Site": configPage({
tagline: "Select a Slack channel from a dropdown menu",
elements: {
"Sharepoint Site": dataSourceConfigVar({
stableKey: "select-slack-channel",
dataSource: {
component: "sharepoint",
key: "listSites",
values: {
connection: { configVar: "Microsoft Sharepoint Connection" },
},
},
}),
},
}),
```
BUT when you go to build and import …
> Fix converting component dataSources when registry and component key differ

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/ComponentRegistry.ts
Some data sources require you to concatenate strings together to form an input. For example, if you're building a Sharepoint integration you may first ask a customer to connect to Sharepoint, then ask them to select a Sharepoint Site from a dropdown menu, and finally ask them to select a drive within their selected sharepoint site.
In the low-code designer, you would concatenate your Sharepoint Site config variable between `/sites/` and `/drives` to form a directory, like this:
Currently, code-native does not allow for such concatenation.
This PR extends reference data source input values, so that you can specify `template` instead of `value` or `configVar`, and can supply a template like `template: "/sites/{{#Sharepoint Site}}/drives"`.
This `configPages.ts` and video demo the template …
> Support templated inputs for referenced data sources

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.ts
Scoped config variables are treated specially in the configuration wizard. In the low-code designer, YAML definitions (left) do _not_ contain SCVs within `configPages.*.elements`. In code-native (right), they currently do. That's a mistake.
Similarly, in low-code (left) SCVs have `meta.*` visibility settings. In code-native (right) they don't.
This PR fixes both of those issues, so code-native integration adhere to the standard that low-code integrations use.
This resolves the issue where a user may see a red toaster `Inputs cannot be empty` alert when using scoped config variables in code native.
> Fix scoped config variable visibility

- packages/spectral/package.json
- packages/spectral/src/serverTypes/context.ts
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/serverTypes/perform.ts
- packages/spectral/src/testing.ts
A bug was reported where, when defining `onInstanceDeploy` and `onInstanceDelete` methods for a CNI flow, `context.components` was unavailable.
This PR makes it so `context.components` is exposed in all CNI-related contexts. To achieve this I did a bit of refactoring, including:
* moving the logic for generating component invocation methods from `convertOnExecution` into a shared `createCNIContext` method, and
* moving `createInvokeFlow` from the component `perform` helper file into the `context` helper file.
> Standardize CNI `context.components` availability

- packages/spectral/package.json
- packages/spectral/src/serverTypes/convertIntegration.test.ts
- packages/spectral/src/serverTypes/convertIntegration.ts
- packages/spectral/src/types/ScopedConfigVars.ts
The `isConnectionScopedConfigVariable` type guard needed enhancing as not all values passing through it are guaranteed to even be of the appropriate `ConfigVar` shape.
> Fix HTML elements being handled improperly when processing configPages

- packages/spectral/package.json
- packages/spectral/src/testing.ts
A bug was reported where the `createConfigVars` testing method would not assign the correct keys to created connections. The issue was that `connection.key` was getting set to the connection's display key, rather than its actual key.
> Bugfix: Update test harness connection keys

- packages/spectral/package.json
- packages/spectral/src/serverTypes/context.ts
- packages/spectral/src/serverTypes/convertIntegration.ts
We came across issues where attempts to build context for triggers and actions wouldn't work in testing scenarios because `context._components` was undefined. This PR fills in the gaps with no-ops.
Verified on local environment that you should be able to properly test management triggers via test harness after this.
> context._components fallbacks for testing use cases

- packages/spectral/package.json
- packages/spectral/src/generators/componentManifest/helpers.ts
- packages/spectral/src/generators/componentManifest/templates/actions/action.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/connections/connection.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/dataSources/dataSource.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/partials/inputs.ejs
- packages/spectral/src/generators/utils/camelizeLowercaseType.ts
We were running into issues where:
1. Certain dataSourceTypes and input types were coming back from the API in all caps, and then not getting camelized properly in the generated manifest (e.g. `OBJECTSELECTION => objectselection`, when the typechecker wants `objectSelection`).
2. Some hyphenated component keys weren't getting camelized and resulting in bad constant names
Re: issue 1, Unfortunately we can't just toss `src/manifests` into generated tsconfig excludes, so we have to actually address this. Put in a manual map to re-camelize these types so manifests generated via API will actually build.
**Notes:**
* valuelist and keyvaluelist do not need treatment
* I am leaving the version bump off for now -- I see some other changes in flight and I'll just wait until the dust has settled to …
> Bugfix - Component manifest generation: Add camelcase when needed

- packages/spectral/src/generators/componentManifest/templates/actions/action.ts.ejs
Almost every action has a key that is already camel-cased. `sendSlackMessage`, etc.
Keys do not need to be camel-cased, though. They can contain hyphens, like the [Compute MD5-SHA1 Hash](https://prismatic.io/docs/components/hash/#compute-md5-sha1-hash) action, which has a key of `computemd5-sha1`.
If you generate a manifest for the `hash` component, you get erronous TypeScript with hyphens that are interpreted as as minus signs.
```
export const computemd5Sha1 = {
key: "computemd5-sha1",
perform: async <TReturn>(values: Computemd5Sha1Values): Promise<TReturn> => {
const context = requireContext();
return ((await context.components.hash.computemd5) -
sha1({ ...values })) as TReturn;
},
```
You end up with TypeScript errors on build
```
ERROR in …
```
> Ensure we reference action by camel-cased key to handle actions with hyphens in their keys

- packages/spectral/package.json
- packages/spectral/src/generators/cniComponentManifest/index.ts
Tested by setting the access token to an intentionally invalid string. Most of the diff here is just formatting changes from putting stuff into a try/catch block.
> Bugfix: cni-component-manifest - Throw readable error if there is an API request failure

- packages/spectral/package.json
- packages/spectral/src/generators/cniComponentManifest/cli.ts
- packages/spectral/src/generators/cniComponentManifest/index.ts
- packages/spectral/src/generators/cniComponentManifest/types.ts
- packages/spectral/src/generators/componentManifest/createConnections.ts
- packages/spectral/src/generators/componentManifest/createDataSources.ts
- packages/spectral/src/generators/componentManifest/createTriggers.ts
- packages/spectral/src/generators/componentManifest/templates/connections/connection.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/dataSources/dataSource.ts.ejs
- packages/spectral/src/generators/componentManifest/templates/triggers/trigger.ts.ejs
- packages/spectral/src/index.ts
- packages/spectral/src/serverTypes/asyncContext.ts
Users can define their own custom component keys in their registries, for example:
```
"custom-slack": slack,
"ms-intune": msIntune,
```
Instead of:
```
slack,
msIntune,
```
Our wrapper functions were initially assuming that all component keys in the registry would just be camel-cased versions of the official key, which is not so.
No DX changes will be required of users, though anyone affected by this issue will need to regenerate their manifests.
* Introduced new `asyncLocalStorage` wrapper around `convertIntegration` to give access to full definition at key points in convert process
* Added utility for locating the user-defined component key in a component manifest (shout-out to Bryan for figuring out the types)
* Updated wrapper functions to lazily fetch component keys at convert time …
> Make manifest wrapper functions compatible with user-defined component keys
